# -*- coding: utf-8 -*-
"""filtering.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18J1NtA2-ogybpcmwIdiMAlFUM5K72Z-J
"""

from google.colab import drive
drive.mount('/content/drive')

pip install kss

!pip install pyngrok

!pip install transformers[torch] kss pyngrok fastapi uvicorn python-multipart

# -----------------------------------------------------
# 2단계: TextFilter 클래스 및 FastAPI 앱 정의
# (필요한 모든 코드를 이 셀 하나에 통합)
# -----------------------------------------------------
import torch
from transformers import AutoTokenizer, BertForSequenceClassification
from typing import Set
import re # <-- 정규표현식 라이브러리 추가
import kss
from fastapi import FastAPI
from pydantic import BaseModel
from contextlib import asynccontextmanager
import nest_asyncio
from pyngrok import ngrok
import uvicorn
import re # <-- 정규표현식 라이브러리 추가

# --- TextFilter 클래스 정의 (엔진 부분) ---
class TextFilter:
    def __init__(self, model_path: str, bad_words_file: str):
        print("필터 시스템을 초기화합니다...")
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.tokenizer = AutoTokenizer.from_pretrained(model_path)
        self.model = BertForSequenceClassification.from_pretrained(model_path)
        self.model.to(self.device)
        self.model.eval()
        self.bad_words: Set[str] = self._load_bad_words(bad_words_file)

        # [추가] 욕설을 한 번에 찾기 위한 정규표현식 패턴 생성
        if self.bad_words:
            self.profanity_pattern = re.compile("|".join(re.escape(word) for word in self.bad_words))
        else:
            self.profanity_pattern = None

        print(f" - 모델: {model_path}")
        print(f" - 욕설 단어: {len(self.bad_words):,} 개")
        print("초기화 완료.")

    def _load_bad_words(self, file_path: str) -> Set[str]:
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                return {line.strip() for line in f if line.strip()}
        except FileNotFoundError:
            print(f"경고: '{file_path}' 파일을 찾을 수 없습니다.")
            return set()

    # [신규] 욕설을 '**'로 마스킹하는 메서드
    def mask_profanity(self, text: str) -> str:
        """
        문장 내의 모든 욕설을 '**'로 변경합니다.
        """
        if self.profanity_pattern:
            return self.profanity_pattern.sub("**", text)
        return text

    def _predict_context_intensity(self, text: str, max_length: int = 256) -> float:
        inputs = self.tokenizer(text, padding="max_length", truncation=True, max_length=max_length, return_tensors="pt").to(self.device)
        with torch.no_grad():
            logits = self.model(**inputs).logits
            intensity_score = logits.squeeze().item()
        return intensity_score

    # [수정] 이 메서드는 이제 AI 점수만 확인하도록 역할 변경
    def judge_by_intensity(self, text: str, threshold: float = 2.0) -> bool:
        """
        AI 모델의 점수만으로 문장이 부적절한지 판단합니다.
        (True: 부적절, False: 통과)
        """
        intensity = self._predict_context_intensity(text)
        print(f" -> (\"{text[:15]}...\" 점수: {intensity:.4f})")

        if intensity >= threshold:
            print(f"   -> (결과: 점수({intensity:.2f})가 기준점({threshold}) 이상이므로 차단)")
            return True

        print("   -> (결과: 통과)")
        return False

# --- FastAPI 앱 정의 (차체 부분) ---
MODEL_PATH = "/content/drive/MyDrive/kobert_regression_checkpoints3"
BAD_WORDS_FILE = "/content/drive/MyDrive/dataset/fword_list.txt"
text_filter = None

@asynccontextmanager
async def lifespan(app: FastAPI):
    global text_filter
    text_filter = TextFilter(model_path=MODEL_PATH, bad_words_file=BAD_WORDS_FILE)
    yield

app = FastAPI(title="텍스트 필터링 API", lifespan=lifespan)

class PostContent(BaseModel):
    content: str
class FilteredContent(BaseModel):
    filtered_text: str

@app.post("/filter-text", response_model=FilteredContent)
def filter_text_endpoint(request: PostContent):
    """
    입력된 텍스트의 욕설을 '**'로 마스킹하고,
    AI가 문맥을 판단하여 유해한 문장을 최종 제거합니다.
    """
    original_text = request.content

    # 먼저 텍스트를 문단(\n\n)으로 분리합니다.
    paragraphs = original_text.split('\n\n')

    cleaned_paragraphs = []

    for paragraph in paragraphs:
        # 각 문단 내부의 문장들을 분리합니다.
        try:
            sentences = kss.split_sentences(paragraph)
        except:
            # kss 에러 발생 시, . 기준으로 분리
            sentences = paragraph.split('.')

        safe_sentences = []

        for sentence in sentences:
            # 1. 먼저 욕설 단어를 '**'로 마스킹합니다.
            masked_sentence = text_filter.mask_profanity(sentence.strip())

            # 2. 마스킹된 문장을 AI가 최종 판단합니다.
            if not text_filter.judge_by_intensity(masked_sentence, threshold=2.0):
                safe_sentences.append(masked_sentence)

        # 문단 내의 안전한 문장들을 다시 합칩니다.
        cleaned_paragraph = " ".join(safe_sentences)

        # 안전한 문단만 리스트에 추가합니다.
        if cleaned_paragraph.strip():  # 빈 문단이 아닐 경우에만 추가
            cleaned_paragraphs.append(cleaned_paragraph)

    # 최종적으로 안전한 문단들을 원래의 문단 구분자로 다시 합칩니다.
    cleaned_text = "\n\n".join(cleaned_paragraphs)

    return {"filtered_text": cleaned_text}

# -----------------------------------------------------
# 3단계: 서버 실행 및 ngrok으로 외부 주소 열기
# (사용자님께서 제안하신 더 좋은 방식)
# -----------------------------------------------------
nest_asyncio.apply()

# [핵심!] ngrok 대시보드에서 복사한 Authtoken을 아래 따옴표 안에 붙여넣으세요.
NGROK_AUTH_TOKEN = "331G3xIoUIOvj5ugsma82V6xLSG_89SDaLhu2oYD43Wii4jva"
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

# 이전에 실행되던 ngrok 터널이 있다면 종료
ngrok.kill()

# 8000번 포트로 새로운 터널 열기
public_url = ngrok.connect(8000)
print("="*60)
print(f"✅ Spring의 apiUrl에 복사할 전체 주소:")
print(f"{public_url}/filter-text")
print("="*60)

# Uvicorn 서버 실행
uvicorn.run(app, host="0.0.0.0", port=8000)