# -*- coding: utf-8 -*-
"""필터링학습.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vxcHfyiD129xdVPmFuayMx9BeNCRetJv
"""

# 욕설 필터링 ai

from google.colab import drive
drive.mount('/content/drive')

!pip install transformers[torch] pandas tqdm accelerate datasets

# ---------------------------
# 1. 필수 라이브러리 import
# ---------------------------
import json
import pandas as pd
import torch
import os
from torch.utils.data import DataLoader
from transformers import AutoTokenizer, BertForSequenceClassification, BertModel, get_linear_schedule_with_warmup
from sklearn.model_selection import train_test_split
from tqdm.auto import tqdm
from datasets import Dataset
import torch.nn as nn
from torch.cuda import amp

# =================================================================
# PART 1: 데이터 전처리 (JSON 파일 병합 및 분리)
# =================================================================
print("===== PART 1: 데이터 전처리 시작 =====")

# 원본 파일 경로 설정
file_paths = [
    '/content/drive/MyDrive/dataset/talksets-train-1_aihub.json',
    '/content/drive/MyDrive/dataset/talksets-train-2.json',
    '/content/drive/MyDrive/dataset/talksets-train-3.json',
    '/content/drive/MyDrive/dataset/talksets-train-4.json',
    '/content/drive/MyDrive/dataset/talksets-train-5.json'
]

all_data = []
print("원본 JSON 파일들을 불러오는 중...")
for path in tqdm(file_paths):
    with open(path, 'r', encoding='utf-8') as f:
        data = json.load(f)

        talkset_list = []
        if isinstance(data, dict) and 'talksets' in data:
            talkset_list = data['talksets']
        elif isinstance(data, list):
            talkset_list = data
        else:
            print(f"경고: {path} 파일의 구조를 인식할 수 없어 건너뜁니다.")
            continue

        for talkset in talkset_list:
            for sentence in talkset.get('sentences', []):
                if sentence.get('is_immoral', False) and sentence.get('text'):
                    all_data.append({
                        'text': sentence.get('text'),
                        'intensity': sentence.get('intensity', 0.0)
                    })

print(f"\n총 {len(all_data):,}개의 유해 문장 데이터를 추출했습니다.")

df = pd.DataFrame(all_data)
df.dropna(subset=['text', 'intensity'], inplace=True)

train_df, test_df = train_test_split(df, test_size=0.1, random_state=42)

print(f"학습 데이터: {len(train_df):,}개")
print(f"테스트 데이터: {len(test_df):,}개")

train_save_file = '/content/drive/MyDrive/dataset/trainDataset/train_dataset_regression.json'
test_save_file = '/content/drive/MyDrive/dataset/testDataset/test_dataset_regression.json'

train_df.to_json(train_save_file, orient='records', force_ascii=False, indent=4)
test_df.to_json(test_save_file, orient='records', force_ascii=False, indent=4)

print(f"\n성공적으로 파일을 저장했습니다:")
print(f" -> 학습 데이터: {train_save_file}")
print(f" -> 테스트 데이터: {test_save_file}")
print("===== PART 1: 데이터 전처리 완료 =====")

# =================================================================
# PART 2: 모델 학습 준비 및 실행
# =================================================================
print("\n===== PART 2: 모델 학습 시작 =====")

# ---------------------------
# 설정값 (Hyperparameters)
# ---------------------------
MODEL_NAME = "beomi/kcbert-base"
MAX_LENGTH = 256
BATCH_SIZE = 64
LEARNING_RATE = 2e-5
WEIGHT_DECAY = 0.01
NUM_EPOCHS = 10
EARLY_STOPPING_PATIENCE = 3
SAVE_DIR = "/content/drive/MyDrive/kobert_regression_final"

# ---------------------------
# 데이터셋 로드 및 토크나이저 준비
# ---------------------------
train_dataset = Dataset.from_json(train_save_file)
eval_dataset = Dataset.from_json(test_save_file)

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

# ---------------------------
# PyTorch Dataset 클래스 정의 (회귀용)
# ---------------------------
class RegressionDataset(torch.utils.data.Dataset):
    def __init__(self, dataset, tokenizer, max_length):
        self.dataset = dataset
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.dataset)

    def __getitem__(self, idx):
        item = self.dataset[idx]
        text = str(item['text'])
        intensity = float(item['intensity'])

        inputs = self.tokenizer(
            text,
            padding='max_length',
            truncation=True,
            max_length=self.max_length,
            return_tensors='pt'
        )

        input_dict = {key: val.squeeze(0) for key, val in inputs.items()}
        input_dict['labels'] = torch.tensor(intensity, dtype=torch.float)
        return input_dict

train_dataset_pt = RegressionDataset(train_dataset, tokenizer, MAX_LENGTH)
eval_dataset_pt = RegressionDataset(eval_dataset, tokenizer, MAX_LENGTH)

train_loader = DataLoader(train_dataset_pt, batch_size=BATCH_SIZE, shuffle=True)
eval_loader = DataLoader(eval_dataset_pt, batch_size=BATCH_SIZE, shuffle=False)

# ---------------------------
# [수정] Sigmoid를 포함한 커스텀 모델 정의
# ---------------------------
class CustomBertForRegression(nn.Module):
    def __init__(self, model_name):
        super().__init__()
        self.bert = BertModel.from_pretrained(model_name)
        # 마지막 출력층을 직접 정의합니다.
        self.classifier = nn.Sequential(
            nn.Linear(self.bert.config.hidden_size, 1),
            nn.Sigmoid()  # <-- 핵심: 출력을 0과 1 사이로 조정
        )

    def forward(self, input_ids, attention_mask, labels=None):
        outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        pooled_output = outputs.pooler_output
        logits = self.classifier(pooled_output)

        loss = None
        if labels is not None:
            loss_fct = nn.MSELoss()
            loss = loss_fct(logits.squeeze(), labels.squeeze())

        return (loss, logits) if loss is not None else logits

# ---------------------------
# 모델, Optimizer, Loss (회귀용)
# ---------------------------
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# [수정] 우리가 정의한 커스텀 모델을 사용합니다.
model = CustomBertForRegression(MODEL_NAME)
model.to(device)

optimizer = torch.optim.AdamW(model.parameters(), lr=LEARNING_RATE, weight_decay=WEIGHT_DECAY)
scaler = amp.GradScaler() # 자동 혼합 정밀도(AMP) 사용

# ---------------------------
# 학습 스케줄러
# ---------------------------
num_training_steps = len(train_loader) * NUM_EPOCHS
num_warmup_steps = int(num_training_steps * 0.1)

scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=num_warmup_steps,
    num_training_steps=num_training_steps
)

# ---------------------------
# 학습 루프 시작
# ---------------------------
os.makedirs(SAVE_DIR, exist_ok=True)
best_loss = float('inf')
patience_counter = 0

for epoch in range(NUM_EPOCHS):
    print(f"\n===== Epoch {epoch+1} / {NUM_EPOCHS} =====")

    # Training
    model.train()
    total_train_loss = 0
    progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1} Training", leave=True)

    for batch in progress_bar:
        optimizer.zero_grad()

        inputs = batch['input_ids'].to(device)
        masks = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        with amp.autocast():
            loss, logits = model(input_ids=inputs, attention_mask=masks, labels=labels)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()
        scheduler.step()

        total_train_loss += loss.item()
        progress_bar.set_postfix({"loss": f"{loss.item():.4f}"})

    avg_train_loss = total_train_loss / len(train_loader)

    # Evaluation
    model.eval()
    total_eval_loss = 0
    with torch.no_grad():
        for batch in tqdm(eval_loader, desc="Evaluating", leave=False):
            inputs = batch['input_ids'].to(device)
            masks = batch['attention_mask'].to(device)
            labels = batch['labels'].to(device)

            with amp.autocast():
                loss, logits = model(input_ids=inputs, attention_mask=masks, labels=labels)

            total_eval_loss += loss.item()

    avg_eval_loss = total_eval_loss / len(eval_loader)

    print(f"[Epoch {epoch+1}] Train Loss: {avg_train_loss:.4f} | Eval Loss: {avg_eval_loss:.4f}")

    # 모델 저장 (Eval Loss 기준)
    if avg_eval_loss < best_loss:
        best_loss = avg_eval_loss
        patience_counter = 0
        model.bert.save_pretrained(SAVE_DIR) # Bert 몸통 부분만 저장
        tokenizer.save_pretrained(SAVE_DIR)
        torch.save(model.classifier.state_dict(), os.path.join(SAVE_DIR, "classifier.pt")) # 커스텀 헤드 저장
        print(f"   -> Best model saved at epoch {epoch+1} with Eval Loss: {best_loss:.4f}")
    else:
        patience_counter += 1
        if patience_counter >= EARLY_STOPPING_PATIENCE:
            print(f"Early stopping triggered at epoch {epoch+1}")
            break

print("\n===== 학습 완료 =====")