# -*- coding: utf-8 -*-
"""추천시스템.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kp7OiAN-2rlufP5-R_W4_wktcAuPTA0y
"""

# 추천시스템

! pip install pandas

!pip install pyngrok

!pip install fastapi "uvicorn[standard]" requests pandas scikit-learn pydantic pyngrok

import requests
import pandas as pd
from fastapi import FastAPI, HTTPException
from sklearn.metrics.pairwise import cosine_similarity
from pydantic import BaseModel
from typing import List
import warnings
import nest_asyncio
from pyngrok import ngrok
import uvicorn
import threading

# 경고 메시지 무시
warnings.filterwarnings("ignore", category=FutureWarning)

# -------------------------------
# 1. FastAPI 앱 초기화 및 전역 변수 설정
# -------------------------------
app = FastAPI(
    title="추천시스템 API",
    description="두 가지 방식의 추천시스템 모델을 제공합니다."
)

# API 응답 형식을 정의합니다.
class Recommendation(BaseModel):
    product_id: int

# 두 개의 추천 모델을 저장할 전역 변수를 선언합니다.
similarity_df_user = None
similarity_df_order = None

# -------------------------------
# 2. 서버 시작 시 데이터 로드 및 모델 생성
# -------------------------------
@app.on_event("startup")
async def startup_event():
    """
    FastAPI 서버가 시작될 때 한 번만 실행됩니다.
    두 종류의 추천 모델을 미리 생성합니다.
    """
    global similarity_df_user, similarity_df_order

    # --- 1. 원본 데이터 로딩 ---
    base_url = " https://4ca30209f63c.ngrok-free.app/api"
    print("API에서 원본 데이터 로딩을 시작합니다...")
    try:
        # 두 로직에서 모두 사용하므로 원본을 변수에 저장
        orderitems_df_raw = pd.DataFrame(requests.get(f"{base_url}/orderitems").json())
        print("데이터 로딩 성공!")
    except Exception as e:
        print(f"데이터 로딩 실패: {e}")
        return

    # =================================================================
    # 모델 1: A를 구매한 사용자가 많이 구매한 상품
    # =================================================================
    print("\n--- 모델 1 (사용자 기반) 생성 시작 ---")
    orderitems_df = orderitems_df_raw.copy()

    # 3. memberid와 productid 추출
    orderitems_df['memberid'] = orderitems_df.apply(
        lambda row: row['orders']['member']['memberId']
        if 'orders' in row and isinstance(row.get('orders'), dict) and 'member' in row['orders'] else None,
        axis=1
    )
    orderitems_df['productid'] = orderitems_df.apply(
        lambda row: row['product']['productId']
        if 'product' in row and isinstance(row.get('product'), dict) else None,
        axis=1
    )
    orderitems_df = orderitems_df.dropna(subset=['memberid', 'productid', 'quantity'])
    orderitems_df['memberid'] = orderitems_df['memberid'].astype(int)
    orderitems_df['productid'] = orderitems_df['productid'].astype(int)
    orderitems_df['quantity'] = orderitems_df['quantity'].astype(int)

    # 4. 사용자-상품 행렬 생성
    user_item_matrix = orderitems_df.pivot_table(
        index='memberid', columns='productid', values='quantity', aggfunc='sum', fill_value=0
    )

    # 5. 상품 간 유사도 계산 및 전역 변수에 저장
    similarity_df_user = pd.DataFrame(
        cosine_similarity(user_item_matrix.T),
        index=user_item_matrix.columns,
        columns=user_item_matrix.columns
    )
    print("--- 모델 1 (사용자 기반) 생성 완료 ---")

    # =================================================================
    # 모델 2: A를 구매했을 때 함께 구매된 상품
    # =================================================================
    print("\n--- 모델 2 (주문 기반) 생성 시작 ---")
    orderitems_df = orderitems_df_raw.copy()

    # 3. orderid와 productid 추출
    orderitems_df['orderid'] = orderitems_df.apply(
        lambda row: row['orders']['orderId']
        if 'orders' in row and isinstance(row.get('orders'), dict) else None,
        axis=1
    )
    orderitems_df['productid'] = orderitems_df.apply(
        lambda row: row['product']['productId']
        if 'product' in row and isinstance(row.get('product'), dict) else None,
        axis=1
    )
    orderitems_df = orderitems_df.dropna(subset=['orderid', 'productid', 'quantity'])
    orderitems_df['orderid'] = orderitems_df['orderid'].astype(int)
    orderitems_df['productid'] = orderitems_df['productid'].astype(int)
    orderitems_df['quantity'] = orderitems_df['quantity'].astype(int)

    # 4. 주문-상품 행렬 생성
    order_item_matrix = orderitems_df.pivot_table(
        index='orderid', columns='productid', values='quantity', aggfunc='sum', fill_value=0
    )

    # 5. 상품 간 유사도 계산 및 전역 변수에 저장
    similarity_df_order = pd.DataFrame(
        cosine_similarity(order_item_matrix.T),
        index=order_item_matrix.columns,
        columns=order_item_matrix.columns
    )
    print("--- 모델 2 (주문 기반) 생성 완료 ---")
    print("\n[알림] 추천 API 서버가 성공적으로 준비되었습니다.")

    @app.get("/recommend/by-user/{product_id}", response_model=List[Recommendation], tags=["추천 기능"])
    def get_recommendations_by_user(product_id: int):
        """(방법 1) 구매한 **사용자**가 많이 구매한 다른 상품 ID를 추천합니다."""
        if similarity_df_user is None:
            raise HTTPException(status_code=503, detail="사용자 기반 모델이 준비되지 않았습니다.")

        if product_id not in similarity_df_user.columns:
            raise HTTPException(status_code=404, detail="해당 상품에 대한 구매 기록이 없어 추천할 수 없습니다.")

        similar_products = similarity_df_user[product_id].sort_values(ascending=False).drop(product_id)
        rec_ids = list(similar_products[similar_products > 0].head(5).index)

        # [수정] 괄호 오타를 수정했습니다.
        return [{"product_id": pid} for pid in rec_ids]

    @app.get("/recommend/together/{product_id}", response_model=List[Recommendation], tags=["추천 기능"])
    def get_recommendations_together(product_id: int):
        """(방법 2) **한 주문에 함께** 구매된 상품 ID를 추천합니다."""
        if similarity_df_order is None:
            raise HTTPException(status_code=503, detail="주문 기반 모델이 준비되지 않았습니다.")

        if product_id not in similarity_df_order.columns:
            raise HTTPException(status_code=404, detail="해당 상품과 함께 구매된 상품이 없습니다.")

        similar_products = similarity_df_order[product_id].sort_values(ascending=False).drop(product_id)
        rec_ids = list(similar_products[similar_products > 0].head(5).index)

        # [수정] 괄호 오타를 수정했습니다.
        return [{"product_id": pid} for pid in rec_ids]

    @app.get("/", include_in_schema=False)
    def root():
        return {"message": "추천 API 서버가 실행 중입니다. /docs 에서 API 문서를 확인하세요."}

# -----------------------------------------------------
# 3단계: 서버 실행 및 ngrok으로 외부 주소 열기
# -----------------------------------------------------
nest_asyncio.apply()

# [핵심 수정!] ngrok에 '비밀 열쇠(authtoken)' 등록
# 1단계에서 복사한 Authtoken을 아래 따옴표 안에 붙여넣으세요.
NGROK_AUTH_TOKEN = "32ygmkzYj9RQWEI8ihUwE8UTpCo_gvxBEcczHHFRBYUK9feF"
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

# 8000번 포트로 외부 접속 터널 열기
ngrok.kill()
public_url = ngrok.connect(8000)
print(f"\n✅ 서버가 성공적으로 실행되었습니다! 아래 공개 주소로 접속하세요:")
print(public_url)

# Uvicorn 서버 실행
uvicorn.run(app, host="0.0.0.0", port=8000)