# -*- coding: utf-8 -*-
"""추천시스템.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kp7OiAN-2rlufP5-R_W4_wktcAuPTA0y
"""

# 추천시스템

! pip install pandas

!pip install pyngrok

pip install kss

!pip install transformers[torch] kss pyngrok fastapi uvicorn python-multipart

!pip install --upgrade transformers

!pip install fastapi "uvicorn[standard]" requests pandas scikit-learn pydantic pyngrok

!pip install --upgrade pip

!pip install fastapi "uvicorn[standard]" requests pandas scikit-learn pydantic pyngrok transformers[torch] kss

pip install aiohttp

# -----------------------------------------------------
# 1단계: 구글 드라이브 마운트 (가장 중요!)
# -----------------------------------------------------
from google.colab import drive
print("Google Drive를 마운트합니다...")
drive.mount('/content/drive')
print("Google Drive 마운트 완료!")

# -----------------------------------------------------
# 2단계: 라이브러리 임포트
# -----------------------------------------------------
import re
import warnings
import threading
from fastapi import FastAPI, HTTPException
import uvicorn
import nest_asyncio
import requests
from pyngrok import ngrok
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from pydantic import BaseModel
from typing import List, Set
import torch
from transformers import AutoTokenizer, BertForSequenceClassification
import kss

# 경고 메시지 무시
warnings.filterwarnings("ignore")

# --- TextFilter 클래스 정의 (필터링 엔진) ---
class TextFilter:
    def __init__(self, model_path: str, bad_words_file: str):
        print("필터 시스템을 초기화합니다...")
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.tokenizer = AutoTokenizer.from_pretrained(model_path)
        self.model = BertForSequenceClassification.from_pretrained(model_path)
        self.model.to(self.device)
        self.model.eval()
        self.bad_words: Set[str] = self._load_bad_words(bad_words_file)
        print(f"필터 모델: {model_path}")
        print(f"욕설 단어: {len(self.bad_words):,} 개 로드됨")
        print("필터 초기화 완료.")

    def _load_bad_words(self, file_path: str) -> Set[str]:
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                return {line.strip() for line in f if line.strip()}
        except FileNotFoundError:
            print(f"WARNING: '{file_path}' 파일을 찾을 수 없습니다.")
            return set()

    def mask_profanity(self, text: str) -> str:
        masked_text = text
        for bad_word in self.bad_words:
            pattern = re.compile(re.escape(bad_word), re.IGNORECASE)
            def replacer(match):
                return '♡' * len(match.group(0))
            masked_text = pattern.sub(replacer, masked_text)
        return masked_text

    def judge_by_intensity(self, text: str, threshold: float = 1.8) -> bool:
        if not text.strip(): return False
        inputs = self.tokenizer(text, padding="max_length", truncation=True, max_length=256, return_tensors="pt").to(self.device)
        with torch.no_grad():
            logits = self.model(**inputs).logits
            intensity_score = logits.squeeze().item()
        print(f"문장: '{text}...' | AI 점수: {intensity_score:.4f}")
        return intensity_score >= threshold

# --- FastAPI 앱 초기화 및 전역 변수 설정 ---
app = FastAPI(title="통합 AI API (추천 + 필터링)")

# 모델들을 저장할 전역 변수
similarity_df_user = None
similarity_df_order = None
text_filter = None

# --- 서버 시작 시 모든 모델을 한 번에 로드 (동기 버전) ---
@app.on_event("startup")
def startup_event():
    global similarity_df_user, similarity_df_order, text_filter

    # --- 1. 추천 모델 생성 ---
    base_url = "https://46563163c051.ngrok-free.app/api"
    print("API에서 추천 데이터 로딩을 시작합니다...")

    try:
        orderitems_df_raw = pd.DataFrame(requests.get(f"{base_url}/orderitems").json())
        print("추천 데이터 로딩 성공!")

        # 모델 1: 사용자 기반
        print("\n--- 추천 모델 1 (사용자 기반) 생성 시작 ---")
        df1 = orderitems_df_raw.copy()
        df1['memberid'] = df1.apply(lambda r: r.get('orders', {}).get('member', {}).get('memberId'), axis=1)
        df1['productid'] = df1.apply(lambda r: r.get('product', {}).get('productId'), axis=1)
        df1.dropna(subset=['memberid', 'productid', 'quantity'], inplace=True)
        if not df1.empty:
            df1[['memberid', 'productid', 'quantity']] = df1[['memberid', 'productid', 'quantity']].astype(int)
            user_item_matrix = df1.pivot_table(index='memberid', columns='productid', values='quantity', aggfunc='sum', fill_value=0)
            if not user_item_matrix.empty:
                similarity_df_user = pd.DataFrame(cosine_similarity(user_item_matrix.T), index=user_item_matrix.columns, columns=user_item_matrix.columns)
        print("--- 추천 모델 1 생성 완료 ---")

        # 모델 2: 주문 기반
        print("\n--- 추천 모델 2 (주문 기반) 생성 시작 ---")
        df2 = orderitems_df_raw.copy()
        df2['orderid'] = df2.apply(lambda r: r.get('orders', {}).get('orderId'), axis=1)
        df2['productid'] = df2.apply(lambda r: r.get('product', {}).get('productId'), axis=1)
        df2.dropna(subset=['orderid', 'productid', 'quantity'], inplace=True)
        if not df2.empty:
            df2[['orderid', 'productid', 'quantity']] = df2[['orderid', 'productid', 'quantity']].astype(int)
            order_item_matrix = df2.pivot_table(index='orderid', columns='productid', values='quantity', aggfunc='sum', fill_value=0)
            if not order_item_matrix.empty:
                similarity_df_order = pd.DataFrame(cosine_similarity(order_item_matrix.T), index=order_item_matrix.columns, columns=order_item_matrix.columns)
        print("--- 추천 모델 2 생성 완료 ---")

    except Exception as e:
        print(f"추천 모델 생성 실패: {e}")
        # 실패 시에도 필터링 모델은 로드
        pass

    # --- 2. 필터링 모델 생성 ---
    print("\n--- 필터링 모델 생성 시작 ---")
    MODEL_PATH = "/content/drive/MyDrive/kobert_regression_checkpoints3"
    BAD_WORDS_FILE = "/content/drive/MyDrive/dataset/fword_list.txt"
    text_filter = TextFilter(model_path=MODEL_PATH, bad_words_file=BAD_WORDS_FILE)
    print("--- 필터링 모델 생성 완료 ---")

    print("\n[알림] 모든 모델이 성공적으로 준비되었습니다.")

# --- API 요청/응답 형식(DTO) 정의 ---
class Recommendation(BaseModel):
    product_id: int

class PostContent(BaseModel):
    title: str
    content: str

class FilteredContent(BaseModel):
    filtered_title: str
    filtered_content: str

# --- API 엔드포인트(API 주소) 정의 ---
@app.get("/recommend/by-user/{product_id}", response_model=List[Recommendation], tags=["추천 기능"])
def get_recommendations_by_user(product_id: int):
    if similarity_df_user is None:
        raise HTTPException(status_code=503, detail="모델 준비 안됨")
    if product_id not in similarity_df_user.columns:
        raise HTTPException(status_code=404, detail="상품 기록 없음")
    similar_products = similarity_df_user[product_id].sort_values(ascending=False).drop(product_id)
    rec_ids = list(similar_products[similar_products > 0].head(5).index)
    return [{"product_id": pid} for pid in rec_ids]

@app.get("/recommend/together/{product_id}", response_model=List[Recommendation], tags=["추천 기능"])
def get_recommendations_together(product_id: int):
    if similarity_df_order is None:
        raise HTTPException(status_code=503, detail="모델 준비 안됨")
    if product_id not in similarity_df_order.columns:
        raise HTTPException(status_code=404, detail="상품 기록 없음")
    similar_products = similarity_df_order[product_id].sort_values(ascending=False).drop(product_id)
    rec_ids = list(similar_products[similar_products > 0].head(5).index)
    return [{"product_id": pid} for pid in rec_ids]

@app.post("/filter-text", response_model=FilteredContent, tags=["필터링 기능"])
def filter_text_endpoint(request: PostContent):
    if text_filter is None:
        raise HTTPException(status_code=503, detail="필터 모델 준비 안됨")

    original_title = request.title
    original_content = request.content

    print("\n--- API 호출 ---")
    print(f"입력 원본 제목: '{original_title}'")
    print(f"입력 원본 내용:\n'{original_content}'")

    filtered_title = text_filter.mask_profanity(original_title)

    lines = original_content.split('\n')
    filtered_lines = []

    for line in lines:
        try:
            sentences = kss.split_sentences(line.strip())
        except:
            sentences = line.strip().split('.')

        safe_sentences = []
        for sentence in sentences:
            if not sentence.strip(): continue

            masked_sentence = text_filter.mask_profanity(sentence)
            if not text_filter.judge_by_intensity(masked_sentence):
                safe_sentences.append(masked_sentence)

        cleaned_line = " ".join(safe_sentences)

        if cleaned_line.strip():
            filtered_lines.append(cleaned_line)

    filtered_content_text = "<br>".join(filtered_lines)

    final_filtered_content = filtered_content_text

    print("\n--- 필터링 결과 ---")
    print(f"전달될 필터링 제목: '{filtered_title}'")
    print(f"전달될 필터링 내용:\n'{final_filtered_content}'")
    print("------------------")

    return {
        "filtered_title": filtered_title,
        "filtered_content": final_filtered_content,
    }

# -----------------------------------------------------
# 3단계: 통합 서버 실행 및 ngrok으로 주소 열기
# -----------------------------------------------------
nest_asyncio.apply()

NGROK_AUTH_TOKEN = "331G3xIoUIOvj5ugsma82V6xLSG_89SDaLhu2oYD43Wii4jva"
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

# 기존 터널이 있다면 종료하고 새로 연결
ngrok.kill()
public_url = ngrok.connect(8000)
print(f"\n✅ 통합 API 서버가 실행되었습니다! 아래 공개 주소로 모든 기능을 호출할 수 있습니다:")
print(public_url)
print(f"📜 API 문서 및 테스트 페이지: {public_url}/docs")

# Uvicorn 서버 실행
uvicorn.run(app, host="0.0.0.0", port=8000)